/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#ifndef _Included_com_example_test_LoaderApplication
#define _Included_com_example_test_LoaderApplication
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_com_example_demo_NativeFunc_init
  (JNIEnv * env, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
